### ISSUE TITLE
Questions about how to use Wiera

### ISSUE THREAD

**Issue by LiPengze97** [dcsg-umn/wiera#3]
Hello, Wiera is an interesting system, and I want to try it.
However, I encountered with several problems. I followed the instructions from the [setup page](http://dcsg.cs.umn.edu/Projects/Wiera/setup.html) and another issue to test it locally. The Wiera Central and Local Server can be started, but when I tried to start the client, it always want to connet with 55555
```
root@node0:~/wiera/wieralocalserver$ ./run_client -w127.0.0.1 -p55559 -fstore_and_retrieve.json
Failed to connect to IP:127.0.0.1 port:55555
Failed create connection to peer.
```
however, the wiera server is on 55559
```
root@node0:~/wiera/wieracentral$ python wiera.py
PolicyManager is running.
[Wiera] Starting applications server port:55558[TSM] Local Server Manager is ready for Local Server port:55559

[TSM] node0.wanagent.cascade-pg0.utah.cloudlab.us(127.0.0.1:34725) is registered.
```
It really makes me confuse, and whats the difference between wclient and client? thanks !

**Comment by LiPengze97** [comment]
OK, the previous problems are caused by the missing args from the script run_client, run_wclient, after I add $1 $2 to the run_client and run_wclient, it works.
However, I met new problems.
I use the command `./run_wclient -w127.0.0.1 -fstore_and_retrieve.json`
and I type the start
```
start
org.apache.thrift.TApplicationException: Unknown function startWieraInstance
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
        at umn.dcsg.wieralocalserver.thriftinterfaces.ApplicationToWieraIface$Client.recv_startWieraInstance(ApplicationToWieraIface.java:73)
        at umn.dcsg.wieralocalserver.thriftinterfaces.ApplicationToWieraIface$Client.startWieraInstance(ApplicationToWieraIface.java:60)
        at umn.dcsg.wieralocalserver.clients.WieraInstanceClient.startInstance(WieraInstanceClient.java:69)
        at umn.dcsg.wieralocalserver.clients.WieraInstanceClient.startInstance(WieraInstanceClient.java:63)
        at umn.dcsg.wieralocalserver.test.WieraClientCLI.main(WieraClientCLI.java:167)
Failed to start Wiera instance
```
what can I do for this? thanks!
